apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-test-script
  namespace: k6-operator-system
data:
  test.js: |
    import http from 'k6/http';
    import { sleep, check } from 'k6';

    export const options = {
      vus: 10,
      duration: '30s',
      thresholds: {
        http_req_duration: ['p(95)<500'],
        http_req_failed: ['rate<0.1'],
      },
    };

    export default function () {
      const response = http.get('https://test.k6.io/');
      
      check(response, {
        'status is 200': (r) => r.status === 200,
        'response time < 500ms': (r) => r.timings.duration < 500,
      });
      
      sleep(1);
    }

    export function handleSummary(data) {
      return {
        'summary.json': JSON.stringify(data, null, 2),
      };
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: load-test-script
  namespace: k6-operator-system
data:
  test.js: |
    import http from 'k6/http';
    import { sleep, check } from 'k6';

    export const options = {
      stages: [
        { duration: '2m', target: 10 },
        { duration: '5m', target: 10 },
        { duration: '2m', target: 20 },
        { duration: '5m', target: 20 },
        { duration: '2m', target: 30 },
        { duration: '5m', target: 30 },
        { duration: '2m', target: 0 },
      ],
      thresholds: {
        http_req_duration: ['p(95)<1000'],
        http_req_failed: ['rate<0.1'],
      },
    };

    export default function () {
      const baseUrl = 'https://test.k6.io';
      
      const endpoints = [
        `${baseUrl}/`,
        `${baseUrl}/my_messages.php`,
        `${baseUrl}/contacts.php`,
      ];
      
      endpoints.forEach(url => {
        const response = http.get(url);
        
        check(response, {
          'status is 200': (r) => r.status === 200,
          'response time < 1000ms': (r) => r.timings.duration < 1000,
        });
        
        sleep(Math.random() * 2 + 1);
      });
    }

    export function handleSummary(data) {
      return {
        'load-test-summary.json': JSON.stringify(data, null, 2),
      };
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stress-test-script
  namespace: k6-operator-system
data:
  test.js: |
    import http from 'k6/http';
    import { sleep, check } from 'k6';

    export const options = {
      stages: [
        { duration: '2m', target: 100 },
        { duration: '5m', target: 100 },
        { duration: '2m', target: 200 },
        { duration: '5m', target: 200 },
        { duration: '2m', target: 300 },
        { duration: '5m', target: 300 },
        { duration: '2m', target: 400 },
        { duration: '5m', target: 400 },
        { duration: '10m', target: 0 },
      ],
      thresholds: {
        http_req_duration: ['p(95)<2000'],
        http_req_failed: ['rate<0.1'],
      },
    };

    export default function () {
      const response = http.get('https://test.k6.io/');
      
      check(response, {
        'status is 200': (r) => r.status === 200,
        'response time < 2000ms': (r) => r.timings.duration < 2000,
      });
      
      sleep(0.5);
    }

    export function handleSummary(data) {
      return {
        'stress-test-summary.json': JSON.stringify(data, null, 2),
      };
    }